const initialData = {
  brand: {
    name: "Hikes & Miles",
    tagline: "Explore India, One Trail at a Time",
    email: "namaste@hikesandmiles.in",
    phone: "+919666962337",
    whatsapp: "+919666962337",
    address: "2-3-638/2, Azad Nagar, Amberpet, Hyderabad, Telangana 500013, India",
    heroTitle: "Discover the Soul of Incredible India",
    heroSubtitle: "Sacred pilgrimages, roaring jungles, and Himalayan trails — every journey with us is a story you'll retell forever.",
    accentColor: "#D4500A",
    darkColor: "#0F1F0E",
    socials: {
      instagram: "https://www.instagram.com/hikesandmiles",
      facebook: "https://facebook.com/hikesandmiles",
      twitter: "https://twitter.com/hikesandmiles",
      youtube: "https://youtube.com/@hikesandmiles",
      whatsapp: "https://wa.me/919666962337",
    },
  },
  destinations: [
    { id: 1, name: "Char Dham", state: "Uttarakhand", image: "https://wsrv.nl/?url=images.unsplash.com/photo-1506905925346-21bda4d32df4&w=600&q=80&fit=cover", tag: "Pilgrimage", rating: 4.9, reviews: 5210 },
    { id: 2, name: "Pench National Park", state: "Madhya Pradesh", image: "https://wsrv.nl/?url=images.unsplash.com/photo-1549366021-9f761d040a94&w=600&q=80&fit=cover", tag: "Tiger Safari", rating: 4.8, reviews: 1342 },
    { id: 3, name: "Tadoba Tiger Reserve", state: "Maharashtra", image: "https://wsrv.nl/?url=images.unsplash.com/photo-1561731216-c3a4d99437d5&w=600&q=80&fit=cover", tag: "Tiger Safari", rating: 4.9, reviews: 1876 },
    { id: 4, name: "Tipeshwar Wildlife Sanctuary", state: "Maharashtra", image: "https://wsrv.nl/?url=images.unsplash.com/photo-1602491453631-e2a5ad90a131&w=600&q=80&fit=cover", tag: "Tiger Safari", rating: 4.7, reviews: 643 },
    { id: 5, name: "Leh-Ladakh", state: "Jammu & Kashmir", image: "https://wsrv.nl/?url=images.unsplash.com/photo-1589308078059-be1415eab4c3&w=600&q=80&fit=cover", tag: "High Altitude", rating: 4.9, reviews: 3241 },
    { id: 6, name: "Kerala Backwaters", state: "Kerala", image: "https://wsrv.nl/?url=images.unsplash.com/photo-1607619056574-7b8d3ee536b2&w=600&q=80&fit=cover", tag: "Leisure", rating: 4.8, reviews: 2654 },
    { id: 7, name: "Rajasthan", state: "Rajasthan", image: "https://wsrv.nl/?url=images.unsplash.com/photo-1477587458883-47145ed94245&w=600&q=80&fit=cover", tag: "Heritage", rating: 4.8, reviews: 4102 },
    { id: 8, name: "Spiti Valley", state: "Himachal Pradesh", image: "https://wsrv.nl/?url=images.unsplash.com/photo-1626621341517-bbf3d9990a23&w=600&q=80&fit=cover", tag: "Trekking", rating: 5.0, reviews: 987 },
  ],
  packages: [
    {
      id: 1, name: "Char Dham Yatra – Sacred Circuit", destination: "Yamunotri · Gangotri · Kedarnath · Badrinath", state: "Uttarakhand",
      price: 18999, originalPrice: 24000, duration: "10–14 Days", groupSize: "10–30",
      category: "Pilgrimage", badge: "Most Sacred",
      image: "https://wsrv.nl/?url=images.unsplash.com/photo-1506905925346-21bda4d32df4&w=800&q=80&fit=cover",
      highlights: ["Darshan at all 4 sacred dhams","Helicopter option for Kedarnath","Ganga aarti at Har Ki Pauri","Pandit assistance at every dham","GMVN approved tour"],
      itinerary: [
        { day: 1, title: "Haridwar", desc: "Ganga aarti at Har Ki Pauri. Welcome dinner." },
        { day: 2, title: "Barkot via Mussoorie", desc: "Drive through Dehradun & Mussoorie." },
        { day: 3, title: "Yamunotri Dham", desc: "Trek 6km to Yamunotri temple." },
        { day: 4, title: "Gangotri Darshan", desc: "Drive to Gangotri. Bhagirathi river dip." },
        { day: 5, title: "Kedarnath Trek", desc: "Gaurikund base. Trek or helicopter to Kedarnath." },
      ],
      includes: ["AC vehicle throughout", "All accommodation", "Daily breakfast + dinner", "Pandit services", "Haridwar transfers"],
      rating: 4.9, reviews: 1203,
      tiers: [
        {
          id: "1-10d", days: 10, nights: 9, label: "Express Yatra", price: 18999, originalPrice: 24000,
          highlights: ["All 4 dhams covered","Helicopter for Kedarnath","Pandit assistance","GMVN hotels","Haridwar Ganga aarti"],
          itinerary: [
            { day:1, title:"Arrive Haridwar", desc:"Ganga aarti at Har Ki Pauri. Welcome dinner." },
            { day:2, title:"Drive to Barkot", desc:"Via Mussoorie. Overnight rest." },
            { day:3, title:"Yamunotri Darshan", desc:"Trek or pony to Yamunotri temple." },
            { day:4, title:"Gangotri Darshan", desc:"Drive via Uttarkashi. Bhagirathi river dip." },
            { day:5, title:"Drive to Gaurikund", desc:"Base for Kedarnath." },
            { day:6, title:"Kedarnath by Helicopter", desc:"Helicopter ride + darshan + return." },
            { day:7, title:"Drive to Badrinath", desc:"Via Joshimath. Check in." },
            { day:8, title:"Badrinath Darshan", desc:"Brahma Muhurta darshan. Mana village." },
            { day:9, title:"Return to Haridwar", desc:"Via Rudraprayag & Devprayag sangam." },
            { day:10, title:"Departure", desc:"Airport/railway transfer from Haridwar." },
          ],
          includes: ["9 nights GMVN hotels","All meals (breakfast + dinner)","AC tempo traveller","Kedarnath helicopter","Pandit at each dham"],
        },
        {
          id: "1-12d", days: 12, nights: 11, label: "Classic Yatra", price: 26999, originalPrice: 34000,
          highlights: ["All 4 dhams at relaxed pace","Kedarnath trek 16km with porter","Mana village — India last village","Haridwar & Rishikesh sightseeing","Devprayag Sangam visit"],
          itinerary: [
            { day:1, title:"Arrive Haridwar", desc:"Ganga aarti. Welcome dinner." },
            { day:2, title:"Rishikesh", desc:"Laxman Jhula, ashrams, yoga session." },
            { day:3, title:"Drive to Barkot", desc:"Via Mussoorie hill station." },
            { day:4, title:"Yamunotri Darshan", desc:"6km trek. Cook rice in hot spring." },
            { day:5, title:"Drive to Uttarkashi", desc:"Vishwanath temple visit." },
            { day:6, title:"Gangotri Darshan", desc:"River dip. Aarti. Overnight." },
            { day:7, title:"Drive to Gaurikund", desc:"Base camp for Kedarnath trek." },
            { day:8, title:"Kedarnath Trek & Darshan", desc:"16km trek (porter included). Darshan." },
            { day:9, title:"Descend & Drive to Badrinath", desc:"Via Chopta meadows." },
            { day:10, title:"Badrinath Darshan", desc:"Brahma Muhurta darshan. Mana village." },
            { day:11, title:"Return to Haridwar", desc:"Devprayag sangam stop." },
            { day:12, title:"Departure", desc:"Transfer from Haridwar." },
          ],
          includes: ["11 nights hotels","All meals","AC tempo traveller","Porter for Kedarnath trek","Pandit at each dham","Rishikesh yoga session"],
        },
        {
          id: "1-14d", days: 14, nights: 13, label: "Divine Yatra + Panch Kedar", price: 34999, originalPrice: 43000,
          highlights: ["All Char Dhams + Panch Kedar","Tungnath world highest Shiva temple","Valley of Flowers UNESCO trek","Hemkund Sahib Gurudwara","Auli ski meadows","Gaumukh glacier optional"],
          itinerary: [
            { day:1, title:"Arrive Haridwar", desc:"Ganga aarti. Welcome dinner." },
            { day:2, title:"Rishikesh", desc:"Laxman Jhula, yoga, rafting." },
            { day:3, title:"Drive to Barkot", desc:"Via Mussoorie." },
            { day:4, title:"Yamunotri Darshan", desc:"Trek + hot spring cook." },
            { day:5, title:"Drive to Uttarkashi", desc:"Vishwanath temple." },
            { day:6, title:"Gangotri Darshan", desc:"Bhagirathi dip. Gaumukh trek option." },
            { day:7, title:"Drive to Gaurikund", desc:"Rest for Kedarnath." },
            { day:8, title:"Kedarnath Darshan", desc:"Trek + overnight at temple." },
            { day:9, title:"Tungnath – Panch Kedar", desc:"World highest Shiva temple at 3680m." },
            { day:10, title:"Drive to Joshimath", desc:"Auli cable car. Himalayan views." },
            { day:11, title:"Valley of Flowers / Hemkund", desc:"UNESCO World Heritage trek." },
            { day:12, title:"Badrinath Darshan", desc:"Brahma Muhurta + Mana village." },
            { day:13, title:"Return to Haridwar", desc:"Devprayag + Rudraprayag sangams." },
            { day:14, title:"Departure", desc:"Transfer from Haridwar." },
          ],
          includes: ["13 nights hotels/camps","All meals","AC vehicle","All trek guides & porters","Pandit at each dham","Valley of Flowers permit"],
        },
      ],
    },
    {
      id: 2, name: "Pench Jungle Safari – Mowgli's Land", destination: "Pench National Park", state: "Madhya Pradesh",
      price: 14999, originalPrice: 19000, duration: "4 Days / 3 Nights", groupSize: "2–8",
      category: "Tiger Safari", badge: "Best Seller",
      image: "https://wsrv.nl/?url=images.unsplash.com/photo-1549366021-9f761d040a94&w=800&q=80&fit=cover",
      highlights: [
        "4 game drives (morning + evening) inside Pench core zone",
        "High chance of Royal Bengal Tiger sighting",
        "Also spot Leopard, Wild Dog, Gaur & over 300 bird species",
        "Kipling's Mowgli trail walk with naturalist",
        "Night safari (buffer zone) with spotlight",
      ],
      itinerary: [
        { day: 1, title: "Arrive Nagpur / Seoni", desc: "Transfer to jungle resort. Evening buffer zone safari." },
        { day: 2, title: "Full Safari Day", desc: "5:30am core zone safari. Debrief & naturalist talk. Evening safari." },
        { day: 3, title: "Turia Gate Safari", desc: "Morning Turia gate safari — highest tiger density zone. Birdwatching walk." },
        { day: 4, title: "Morning Safari + Depart", desc: "Last safari at dawn. Transfer to Nagpur airport/station." },
      ],
      includes: ["Pickup/drop Nagpur", "Jungle lodge (3 nights)", "All meals (full board)", "Gypsy Safari + guide + permit fees", "Naturalist-led nature walks"],
      rating: 4.8, reviews: 487,
    },
    {
      id: 3, name: "Tadoba Tiger Safari – Maharashtra's Pride", destination: "Tadoba-Andhari Tiger Reserve", state: "Maharashtra",
      price: 16499, originalPrice: 21000, duration: "4 Days / 3 Nights", groupSize: "2–8",
      category: "Tiger Safari", badge: "Top Rated",
      image: "https://wsrv.nl/?url=images.unsplash.com/photo-1561731216-c3a4d99437d5&w=800&q=80&fit=cover",
      highlights: [
        "Tadoba — Maharashtra's only & most successful Tiger Reserve",
        "One of India's highest tiger densities (90+ tigers)",
        "Also spot Sloth Bear, Leopard, Crocodile & Gaur",
        "Moharli & Kolara gate morning safaris",
        "Expert naturalist with tracker for trail reading",
      ],
      itinerary: [
        { day: 1, title: "Arrive Chandrapur", desc: "Transfer to eco-lodge near Moharli gate. Evening safari." },
        { day: 2, title: "Core Zone Full Day", desc: "5am Moharli gate safari. Camera tips session. Evening Kolara gate." },
        { day: 3, title: "Kolara Deep Zone", desc: "Early Kolara zone — famous tigress territory. Afternoon bird walk." },
        { day: 4, title: "Sunrise Safari + Depart", desc: "Final dawn safari. Breakfast. Transfer to Nagpur." },
      ],
      includes: ["Pickup/drop Nagpur or Chandrapur", "Eco-lodge (3 nights)", "All meals", "All safari permits + gypsy + guide", "Naturalist throughout"],
      rating: 4.9, reviews: 612,
    },
    {
      id: 4, name: "Tipeshwar Tiger Safari – Hidden Gem", destination: "Tipeshwar Wildlife Sanctuary", state: "Maharashtra",
      price: 12999, originalPrice: 16500, duration: "3 Days / 2 Nights", groupSize: "2–6",
      category: "Tiger Safari", badge: "Hidden Gem",
      image: "https://wsrv.nl/?url=images.unsplash.com/photo-1602491453631-e2a5ad90a131&w=800&q=80&fit=cover",
      highlights: [
        "Maharashtra's most underrated tiger sanctuary — fewer crowds, pure wild",
        "Resident tiger families with regularly tracked individuals",
        "Also spot Leopard, Wild Dog, Hyena, Jackal & Nilgai",
        "Intimate 6-seater gypsy — no large tourist vehicles",
        "Connecting corridor between Tadoba & Navegaon reserves",
      ],
      itinerary: [
        { day: 1, title: "Arrive Pandharkawada", desc: "Check-in forest camp. Briefing & evening buffer safari." },
        { day: 2, title: "Sunrise Core Safari", desc: "5am deep zone entry. Afternoon jungle walk with tracker." },
        { day: 3, title: "Morning Safari + Depart", desc: "Last safari at dawn. Transfer back to Yavatmal or Nagpur." },
      ],
      includes: ["Pickup/drop Yavatmal or Nagpur", "Forest camp (2 nights)", "All meals", "All permits + gypsy + guide", "Expert tracker"],
      rating: 4.7, reviews: 218,
    },
    {
      id: 5, name: "Leh-Ladakh Bike Expedition", destination: "Leh & Nubra Valley", state: "Jammu & Kashmir",
      price: 28999, originalPrice: 36000, duration: "10 Days / 9 Nights", groupSize: "6–16",
      category: "Adventure", badge: "Epic Ride",
      image: "https://wsrv.nl/?url=images.unsplash.com/photo-1589308078059-be1415eab4c3&w=800&q=80&fit=cover",
      highlights: [
        "Khardung La — World's highest motorable road at 5359m",
        "Pangong Tso Lake overnight camp",
        "Nubra Valley camel safari on white sand dunes",
        "Thiksey, Hemis & Diskit monastery visits",
        "Royal Enfield Himalayan 411 provided",
      ],
      itinerary: [
        { day: 1, title: "Arrive Leh (3500m)", desc: "Acclimatization. Local market walk. Welcome dinner." },
        { day: 2, title: "Leh City Sightseeing", desc: "Thiksey, Hemis, Shanti Stupa. Bike briefing & checks." },
        { day: 3, title: "Khardung La → Nubra Valley", desc: "Cross the legendary 5359m pass. Descend to Diskit." },
        { day: 4, title: "Nubra Camel Safari", desc: "Diskit Monastery. Sunset camel ride on white dunes." },
        { day: 5, title: "Pangong Tso Lake", desc: "Long ride to the iconic blue lake. Overnight camp." },
      ],
      includes: ["Flights Delhi–Leh–Delhi", "All accommodation & camping", "All meals", "RE Himalayan 411 bike", "Biker guide, mechanic & support vehicle"],
      rating: 4.9, reviews: 341,
    },
    {
      id: 6, name: "Kerala Backwaters & Munnar Escape", destination: "Kochi · Munnar · Alleppey", state: "Kerala",
      price: 12999, originalPrice: 16000, duration: "4–10 Days", groupSize: "2–12",
      category: "Leisure", badge: "Crowd Favourite",
      image: "https://wsrv.nl/?url=images.unsplash.com/photo-1607619056574-7b8d3ee536b2&w=800&q=80&fit=cover",
      highlights: ["Private houseboat stay on Alleppey backwaters","Munnar tea estate walk at golden hour","Periyar wildlife boat safari","Kathakali & Kalaripayattu performance","Kerala Ayurvedic full-body massage session"],
      itinerary: [
        { day: 1, title: "Arrive Kochi", desc: "Fort Kochi heritage walk. Chinese fishing nets. Seafood dinner." },
        { day: 2, title: "Drive to Munnar", desc: "Tea estate tour, Eravikulam National Park." },
        { day: 3, title: "Top Station Trek", desc: "Sunrise hike. Mist valley views. Spice market." },
        { day: 4, title: "Periyar, Thekkady", desc: "Elephant camp visit, bamboo rafting, spice plantation." },
        { day: 5, title: "Alleppey Houseboat", desc: "Board private houseboat. Float through coconut-fringed canals." },
      ],
      includes: ["Flights to/from Kochi", "Hotels + houseboat night", "Daily breakfast + 3 special dinners", "AC vehicle throughout", "Expert local guide"],
      rating: 4.8, reviews: 537,
      tiers: [
        {
          id: "6-4d", days: 4, nights: 3, label: "Quick Escape", price: 12999, originalPrice: 16000,
          highlights: ["Fort Kochi city walk","Munnar tea estates","Alleppey houseboat 1 night","Chinese fishing nets at sunset"],
          itinerary: [
            { day:1, title:"Arrive Kochi", desc:"Fort Kochi walk, Chinese fishing nets, seafood dinner." },
            { day:2, title:"Drive to Munnar", desc:"Tea estate tour, Eravikulam National Park, Top Station." },
            { day:3, title:"Alleppey Houseboat", desc:"Board private houseboat, float through canals." },
            { day:4, title:"Depart from Kochi", desc:"Transfer to airport. Departure." },
          ],
          includes: ["3 nights hotel + 1 night houseboat", "Daily breakfast", "AC vehicle", "Guide"],
        },
        {
          id: "6-7d", days: 7, nights: 6, label: "Classic Kerala", price: 18999, originalPrice: 24000,
          highlights: ["Everything in 4-day plan","Periyar wildlife boat safari","Thekkady spice plantation","Kovalam beach day","Ayurvedic massage session"],
          itinerary: [
            { day:1, title:"Arrive Kochi", desc:"Fort Kochi walk, seafood dinner." },
            { day:2, title:"Drive to Munnar", desc:"Tea estates, Eravikulam NP." },
            { day:3, title:"Thekkady", desc:"Periyar wildlife safari, spice plantation walk." },
            { day:4, title:"Alleppey Houseboat", desc:"Private houseboat overnight." },
            { day:5, title:"Drive to Kovalam", desc:"Beach, sunset, seafood." },
            { day:6, title:"Kovalam & Ayurveda", desc:"Full-body Ayurvedic massage, leisure beach time." },
            { day:7, title:"Depart Trivandrum", desc:"Airport transfer. Departure." },
          ],
          includes: ["6 nights hotels + houseboat", "Daily breakfast + 3 dinners", "AC vehicle throughout", "Expert guide", "Ayurvedic session"],
        },
        {
          id: "6-10d", days: 10, nights: 9, label: "Complete Kerala", price: 24999, originalPrice: 31000,
          highlights: ["Everything in 7-day plan","Wayanad forest trek","Thrissur Pooram (seasonal)","North Kerala temples","Silent Valley National Park","Bekal Fort visit"],
          itinerary: [
            { day:1, title:"Arrive Kochi", desc:"Fort Kochi walk, seafood dinner." },
            { day:2, title:"Drive to Munnar", desc:"Tea estates, Top Station." },
            { day:3, title:"Thekkady", desc:"Periyar wildlife, bamboo rafting." },
            { day:4, title:"Alleppey Houseboat", desc:"Private houseboat overnight." },
            { day:5, title:"Drive to Wayanad", desc:"Edakkal caves, tribal museum." },
            { day:6, title:"Wayanad Trek", desc:"Chembra Peak trek (2100m). Tea & coffee estates." },
            { day:7, title:"Drive to Kozhikode", desc:"Beypore boat yard, spice market, halwa." },
            { day:8, title:"Bekal Fort & North Kerala", desc:"Bekal fort, Kannur beaches, loom weaving." },
            { day:9, title:"Kovalam Beach", desc:"Ayurvedic massage, beach leisure." },
            { day:10, title:"Depart Trivandrum", desc:"Airport transfer. Departure." },
          ],
          includes: ["9 nights hotels + houseboat", "Daily breakfast + 5 dinners", "AC vehicle throughout", "Expert guide", "Wayanad trek guide", "Ayurvedic session"],
        },
      ],
    },
    {
      id: 7, name: "Rajasthan Royal Heritage Tour", destination: "Jaipur · Jodhpur · Jaisalmer · Udaipur", state: "Rajasthan",
      price: 16999, originalPrice: 21000, duration: "7–14 Days", groupSize: "4–20",
      category: "Heritage", badge: "Classic",
      image: "https://wsrv.nl/?url=images.unsplash.com/photo-1477587458883-47145ed94245&w=800&q=80&fit=cover",
      highlights: ["Sunset at Mehrangarh Fort battlements","Lake Palace dinner, Udaipur","Overnight camel trek into Thar Desert","Amber Fort sunrise visit","Blue Pottery & Block-Printing workshop"],
      itinerary: [
        { day: 1, title: "Arrive Jaipur — Pink City", desc: "Heritage haveli check-in. Evening at Chokhi Dhani." },
        { day: 2, title: "Amber Fort & City Palace", desc: "Elephant ride, Jantar Mantar, bazaars." },
        { day: 3, title: "Drive to Jodhpur", desc: "Ranakpur Jain Temples en route. Arrive Blue City." },
        { day: 4, title: "Mehrangarh & Thar Desert", desc: "Fort tour. Drive to Jaisalmer. Camel dune sunset." },
        { day: 5, title: "Desert Camp Night", desc: "Overnight camp. Folk music & bonfire. Stargazing." },
      ],
      includes: ["Train transfers (Shatabdi/Vande Bharat)", "Heritage hotels & desert camp", "Daily breakfast + 4 dinners", "Private AC vehicle", "English-speaking guide"],
      rating: 4.8, reviews: 689,
      tiers: [
        {
          id: "7-7d", days: 7, nights: 6, label: "Golden Triangle", price: 16999, originalPrice: 21000,
          highlights: ["Jaipur Pink City","Amber Fort elephant ride","Jodhpur Blue City","Mehrangarh Fort","Jaisalmer camel safari","Desert camp night"],
          itinerary: [
            { day:1, title:"Arrive Jaipur", desc:"Heritage haveli. Evening at Chokhi Dhani." },
            { day:2, title:"Amber Fort & City Palace", desc:"Elephant ride, Jantar Mantar, bazaars." },
            { day:3, title:"Drive to Jodhpur", desc:"Ranakpur Jain Temples en route." },
            { day:4, title:"Mehrangarh Fort", desc:"Fort tour, zip-line. Spice market walk." },
            { day:5, title:"Drive to Jaisalmer", desc:"Sam sand dunes. Camel sunset safari." },
            { day:6, title:"Desert Camp", desc:"Overnight luxury camp, folk music, bonfire." },
            { day:7, title:"Return & Depart", desc:"Drive to Jodhpur. Departure flight." },
          ],
          includes: ["6 nights hotels + desert camp", "Daily breakfast + 3 dinners", "AC vehicle", "Guide"],
        },
        {
          id: "7-10d", days: 10, nights: 9, label: "Royal Rajasthan", price: 22499, originalPrice: 28000,
          highlights: ["Everything in 7-day plan +","Udaipur Lake Palace dinner","City of Lakes boat ride","Pushkar camel fair (seasonal)","Ranthambore wildlife safari","Stepwells of Jodhpur"],
          itinerary: [
            { day:1, title:"Arrive Jaipur", desc:"Heritage haveli. Chokhi Dhani dinner." },
            { day:2, title:"Amber Fort", desc:"Elephant ride, City Palace, Jantar Mantar." },
            { day:3, title:"Pushkar", desc:"Holy lake, Brahma temple, camel market." },
            { day:4, title:"Ranthambore Safari", desc:"Tiger reserve game drive." },
            { day:5, title:"Drive to Jodhpur", desc:"Ranakpur Jain Temples en route." },
            { day:6, title:"Mehrangarh Fort", desc:"Fort, zip-line, blue city walk." },
            { day:7, title:"Jaisalmer", desc:"Desert drive, Patwon ki Haveli." },
            { day:8, title:"Desert Camp", desc:"Luxury tent, camel dunes, folk music." },
            { day:9, title:"Drive to Udaipur", desc:"City of Lakes, Pichola boat ride." },
            { day:10, title:"Udaipur & Depart", desc:"City Palace, Lake Palace dinner. Departure." },
          ],
          includes: ["9 nights heritage hotels + camp", "Daily breakfast + 5 dinners", "AC vehicle", "All guide fees", "Ranthambore permit"],
        },
        {
          id: "7-14d", days: 14, nights: 13, label: "Complete Rajasthan", price: 31999, originalPrice: 39000,
          highlights: ["Everything in 10-day plan +","Bikaner camel research farm","Shekhawati frescoed havelis","Chittorgarh fortress","Mount Abu Dilwara Temples","Bundi step wells & palace"],
          itinerary: [
            { day:1, title:"Arrive Jaipur", desc:"Heritage haveli. Chokhi Dhani." },
            { day:2, title:"Amber Fort & Palaces", desc:"Full Jaipur sightseeing." },
            { day:3, title:"Shekhawati", desc:"Mandawa painted havelis. Open-air art gallery." },
            { day:4, title:"Bikaner", desc:"Junagarh Fort, camel research station." },
            { day:5, title:"Jaisalmer", desc:"Golden Fort, Patwon ki Haveli." },
            { day:6, title:"Desert Safari", desc:"Sam sand dunes, camel ride." },
            { day:7, title:"Desert Camp", desc:"Luxury camp, stars, folk performances." },
            { day:8, title:"Jodhpur", desc:"Mehrangarh, Jaswant Thada, blue lanes." },
            { day:9, title:"Mount Abu", desc:"Dilwara Jain Temples, Nakki Lake sunset." },
            { day:10, title:"Udaipur", desc:"City Palace, Pichola Lake boat." },
            { day:11, title:"Udaipur & Chittorgarh", desc:"Vijay Stambha, Rana Kumbha Palace." },
            { day:12, title:"Bundi", desc:"Taragarh Fort, Bundi Palace, step wells." },
            { day:13, title:"Ranthambore Safari", desc:"Tiger reserve full-day safari." },
            { day:14, title:"Return Jaipur & Depart", desc:"Airport transfer. Departure." },
          ],
          includes: ["13 nights hotels + desert camp", "Daily breakfast + 7 dinners", "AC vehicle throughout", "All guides & entry fees", "2 wildlife safaris"],
        },
      ],
    },
    {
      id: 8, name: "Spiti Cold Desert Trek", destination: "Spiti Valley", state: "Himachal Pradesh",
      price: 19999, originalPrice: 25000, duration: "10 Days / 9 Nights", groupSize: "6–14",
      category: "Trekking", badge: "Challenging",
      image: "https://wsrv.nl/?url=images.unsplash.com/photo-1626621341517-bbf3d9990a23&w=800&q=80&fit=cover",
      highlights: [
        "Key Monastery perched at 4166m",
        "Chandratal Lake — the Moon Lake",
        "Pin Valley National Park trek",
        "Zero light pollution stargazing",
        "Local homestay experience in Kaza",
      ],
      itinerary: [
        { day: 1, title: "Arrive Shimla", desc: "Briefing. Overnight guesthouse." },
        { day: 2, title: "Drive to Narkanda", desc: "Scenic Himalayan drive. Apple orchards." },
        { day: 3, title: "Enter Kinnaur", desc: "Sangla Valley. Hanging bridge. Local lunch." },
        { day: 4, title: "Reach Kaza", desc: "Cross Spiti river. Check in homestay." },
        { day: 5, title: "Key Monastery & Kibber", desc: "Visit Asia's highest monastery. Kibber village walk." },
      ],
      includes: ["Bus/jeep transfers throughout", "Guesthouses + camping", "All meals (full board)", "Certified mountain guide", "Permits & camping gear"],
      rating: 5.0, reviews: 278,
    },
  ],
  testimonials: [
    { id: 1, name: "Raghavendra Iyer", location: "Pune, Maharashtra", text: "The Char Dham Yatra with Hikes & Miles was a life-changing experience. Every puja was arranged beautifully, the vehicles were comfortable, and the team was incredibly supportive at high altitudes. I cried at Kedarnath — in the best way.", rating: 5, avatar: "RI", package: "Char Dham Yatra" },
    { id: 2, name: "Sneha Kulkarni", location: "Nagpur, Maharashtra", text: "We spotted a tigress and her two cubs at Tadoba on day one! The naturalist knew exactly where to position the gypsy. Hikes & Miles made every safari feel like a Nat Geo moment. Absolutely thrilling.", rating: 5, avatar: "SK", package: "Tadoba Tiger Safari" },
    { id: 3, name: "Arjun Mehra", location: "Delhi, NCR", text: "Ladakh on a Royal Enfield — a dream I've had for 10 years. The team at Hikes & Miles turned it into reality without a single hitch. The support vehicle saving us near Khardung La was the stuff of legends!", rating: 5, avatar: "AM", package: "Leh-Ladakh Bike Expedition" },
    { id: 4, name: "Priya & Suresh Nair", location: "Bengaluru, Karnataka", text: "Kerala was magical from the first boat ride to the last cup of chai on the houseboat. Hikes & Miles arranged every tiny detail. We didn't have to think about anything — just soak it all in.", rating: 5, avatar: "PN", package: "Kerala Backwaters Escape" },
    { id: 5, name: "Vikram Shinde", location: "Aurangabad, Maharashtra", text: "Tipeshwar is India's best-kept secret. No crowds, no rush — just you and the jungle. Saw a beautiful male tiger within the first hour! Hikes & Miles is the only team operating deep-zone permits here.", rating: 5, avatar: "VS", package: "Tipeshwar Tiger Safari" },
    { id: 6, name: "Ananya Deshmukh", location: "Mumbai, Maharashtra", text: "Pench felt straight out of Jungle Book — literally! Our guide narrated Kipling's stories at each waterhole. The resort was gorgeous and the food was incredible. Couldn't ask for more.", rating: 5, avatar: "AD", package: "Pench Jungle Safari" },
  ],
  offers: [
    { id: 1, title: "Char Dham Early Booking", discount: "₹4000 OFF", code: "DHAM2026", desc: "Book your Char Dham Yatra before April 15 and save big. Limited seats per batch.", expiry: "15 April 2026", color: "#B34700" },
    { id: 2, title: "Safari Combo Deal", discount: "15% OFF", code: "TIGER15", desc: "Book any 2 tiger safari packages together — Pench + Tadoba or Tadoba + Tipeshwar.", expiry: "Ongoing", color: "#1E5C1E" },
    { id: 3, title: "Monsoon Himalaya Special", discount: "₹3000 OFF", code: "HILLS26", desc: "Spiti & Ladakh special July–September. Green valleys, fewer crowds, magical skies.", expiry: "30 June 2026", color: "#1A4A6E" },
    { id: 4, title: "Group Pilgrim Discount", discount: "10% OFF", code: "GROUP10", desc: "Groups of 20+ for Char Dham Yatra get special bus allocation & group puja arrangements.", expiry: "Ongoing", color: "#6E4A1A" },
  ],
  blog: [
    { id: 1, title: "Char Dham Yatra 2026 – Complete Preparation Guide", category: "Pilgrimage Guide", date: "March 5, 2026", readTime: "8 min", image: "https://wsrv.nl/?url=images.unsplash.com/photo-1506905925346-21bda4d32df4&w=600&q=80&fit=cover", excerpt: "Everything you need to know before embarking on the holiest circuit in the Himalayas — registration, fitness, packing, and what to expect at each dham.", author: "Pandit Ramesh Bhatt" },
    { id: 2, title: "Tadoba vs Pench vs Tipeshwar — Which Safari is Right for You?", category: "Wildlife Guide", date: "Feb 18, 2026", readTime: "6 min", image: "https://wsrv.nl/?url=images.unsplash.com/photo-1561731216-c3a4d99437d5&w=600&q=80&fit=cover", excerpt: "Three of Maharashtra and MP's finest tiger reserves, each with a unique personality. Our wildlife experts break down the differences so you can choose your perfect jungle escape.", author: "Nikhil Ghorpade" },
    { id: 3, title: "Riding to Khardung La — What Nobody Tells You", category: "Adventure Stories", date: "Jan 30, 2026", readTime: "5 min", image: "https://wsrv.nl/?url=images.unsplash.com/photo-1589308078059-be1415eab4c3&w=600&q=80&fit=cover", excerpt: "Altitude sickness, frozen throttles, and the most stunning road on Earth. A first-person account of the Leh-Ladakh bike expedition that changed everything.", author: "Rohan Salvi" },
    { id: 4, title: "Kerala Houseboat Diaries — 24 Hours on the Backwaters", category: "Travel Stories", date: "Jan 12, 2026", readTime: "4 min", image: "https://wsrv.nl/?url=images.unsplash.com/photo-1607619056574-7b8d3ee536b2&w=600&q=80&fit=cover", excerpt: "What happens when you unplug completely and let the slow rhythm of Kerala's backwaters carry you? A perfect day, from fish curry breakfast to firefly-lit evenings.", author: "Meera Krishnan" },
  ],
  bookings: [
    { id: 1, name: "Suresh Patil", email: "suresh.p@gmail.com", package: "Char Dham Yatra – Sacred Circuit", travelers: 4, date: "2026-05-10", status: "Confirmed", total: 107996, message: "Need wheelchair assistance for elderly parent at Kedarnath." },
    { id: 2, name: "Kavita Rane", email: "kavita.rane@yahoo.in", package: "Tadoba Tiger Safari – Maharashtra's Pride", travelers: 2, date: "2026-04-18", status: "Pending", total: 32998, message: "Prefer Moharli gate both days. Any tiger tracking special?" },
    { id: 3, name: "Aditya Joshi", email: "adi.joshi@outlook.com", package: "Pench Jungle Safari – Mowgli's Land", travelers: 6, date: "2026-06-02", status: "Confirmed", total: 89994, message: "Group of colleagues. Need team-building nature walk too." },
    { id: 4, name: "Sunita Mehta", email: "sunita.m@gmail.com", package: "Leh-Ladakh Bike Expedition", travelers: 2, date: "2026-07-15", status: "Pending", total: 57998, message: "Both of us are beginner bikers. Is this feasible?" },
  ],
  seo: {
    siteTitle: "Hikes & Miles | Best India Tour Packages – Char Dham, Tiger Safaris, Himalayas",
    metaDescription: "Book premium India tour packages with Hikes & Miles. Char Dham Yatra, Pench Safari, Tadoba Safari, Tipeshwar Tiger Safari, Ladakh, Kerala & Rajasthan. Expert-guided, all-inclusive.",
    keywords: "char dham yatra, tiger safari india, tadoba safari, pench national park, tipeshwar safari, ladakh tour, kerala tour, india travel packages",
  },
};

// ── ICONS ─────────────────────────────────────────────────────────────────────

export default initialData;
